name: dyntapy
channels:
  - https://conda.anaconda.org/conda-forge/
  - https://conda.anaconda.org/anaconda
  - anaconda
  - numba
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - numba>=0.55
  - matplotlib
  - osmnx>=1.3.0
  - numpy
  - scipy
  - pip
  - jupyter
  - python-igraph
  - bokeh>=3.0
  - pyproj
  - geojson
  - pandas
  - shapely
  - networkx>=2.7
