#  This file is part of the Traffic Assignment Package developed at KU Leuven.
#  Copyright (c) 2020 Paul Ortmann
#  License: GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007, see license.txt
#  More information at: https://gitlab.mech.kuleuven.be/ITSCreaLab
#  or contact: ITScrealab@kuleuven.be
#
#
dump_cfg: 0
color_scheme: dark_bg
full_tracebacks: 1
show_help: 1
highlight_dumps: 0
debuginfo: 1
debug_typeinfer: 0
dump_annotation: 0
NUMBA_OPT: 1